### ISSUE TITLE
format do not have MediaFormat.KEY_FRAME_RATE,and it cause NullPointerException like 

### ISSUE THREAD

**Issue by RrtoyewxXu** [Jhuster/Android#2]
In Android/MediaDemo 

```
 framerate = format.getInteger(MediaFormat.KEY_FRAME_RATE);
```

format do not have MediaFormat.KEY_FRAME_RATE,and it cause NullPointerException like 

```

 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
 at android.media.MediaFormat.getInteger(MediaFormat.java:524)

```

please tell me how to deal with it
In Android/MediaDemo 

```
 framerate = format.getInteger(MediaFormat.KEY_FRAME_RATE);
```

format do not have MediaFormat.KEY_FRAME_RATE,and it cause NullPointerException like 

```

 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
 at android.media.MediaFormat.getInteger(MediaFormat.java:524)

```

please tell me how to deal with it

**Comment by FairlyMavis** [comment]
you can use MediaFormat.containsKey(MediaFormat.KEY_FRAME_RATE)  to judge whether the mediaFormat has the value
